services:
  redis:
    image: redis:7-alpine
    container_name: archivenet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
  api:
    build: ./API
    container_name: archivenet-api
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./API/.env
    depends_on:
      - redis
    restart: unless-stopped
volumes:
  redis_data:
